apiVersion: apps/v1
kind: Deployment
metadata:
  name: zero-node-app-deployment
  labels:
    app: zero-node-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zero-node-app
  template:
    metadata:
      labels:
        app: zero-node-app
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: server
        image: amiraniv/zero-node:v1.0
        resources:
          requests:
            cpu: "300m"
          limits:
            cpu: "300m"
        livenessProbe:
          httpGet:
            path: "/health"
            port: 3000
        readinessProbe:
          httpGet:
            path: "/ready"
            port: 3000
---

apiVersion: v1
kind: Service
metadata:
  name: zero-node-app-service
spec:
  selector:
    app: zero-node-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
