apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: zero-node-app-scaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: zero-node-app
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 60
